import { University } from './university';

export var UniversityList: University[] =[
  {
    name:"Duke University",
    city:"Durham",
    state:"NC",
    rank:"1",
    colleges:["engineering","fine art","arts & sciences", "business"],
    region:"South East",
    img:"../../assets/duke.jpg",
    saved:"no",
    visible:"yes",
    id:"1",
    geo:"urban",
    type:"private",
    icon:"../../assets/duke_icon.png",
    population:"10k",
  },
  {
    name:"University Of Miami",
     city:"Coral Gables",
     state:"FL",
     rank:"2",
     colleges:[''],
     region:"South East",
     img:'../../assets/UM.jpg',
     saved:"no",
     visible:"yes",
     id:"2",
     geo:"urban",
     type:"private",
     icon:"../../assets/UM_icon.png",
     population:"10k",
   },
  {
    name:"UNC at Chapel Hill",
    city:"Chapel Hill",
    state:"NC",
    rank:"3",
    colleges:[''],
    region:"South East",
    img:'../../assets/unc.jpg',
    saved:"no",
    visible:"yes",
    id:"3",
    geo:"urban",
    type:"private",
    icon:"../../assets/unc_icon.png",
    population:"10k",
  },
  {
    name:"NC State University",
    city:"Raleigh",
    state:"NC",
    rank:"4",
    colleges:[''],
    region:"South East",
    img:'../../assets/ncstate.jpg',
    saved:"no",
    visible:"yes",
    id:"4",
    geo:"urban",
    type:"private",
    icon:"../../assets/ncstate_icon.jpg",
    population:"10k",
  },
  {
    name:"Wichita State University",
    city:"Wichita",
    state:"KS",
    rank:"5",
    colleges:[''],
    region:"Central",
    img:'../../assets/shocker.jpg',
    saved:"no",
    visible:"yes",
    id:"5",
    geo:"rural",
    type:"public",
    icon:"../../assets/shocker_icon.jpg",
    population:"10k",
  }
];
